sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: GP+QWNpaFXdg2fi3ymgC3o3nnxVmfS0UBwjc+MbU1Qf1vsiLsCJXD3PvUp7nXAsaK5Kzoi5fcyEZhUaSRA1TWKktbFuEONYvoPd2DSNKwv5O1RL+Nk0iatdxrasB2d5aAR1t7u2s0b6rOfOyiADT+tmSsMKzxRBGLbr6uipw9LITmNHN7k/IjDJ2r2B9vqaBZL1yi8kwcvR3bsAl5UL05uB0w8RZFm95ZZEeIcL77KS/DNhbfuZsBRNLi0HkA8H0/jlpNZjrEd8MOGjt9W2HFd4zoMGnQmxQY4iyy2luBebfmKll33Uq/4VuWvOaxsyv6O3FxR0yb+NFZRiaMxAKWgkyPRkkJZjs/59J25vUM/9hjU+e8Tz5rAx0oZtetu4CwGukx40ZaFKqn7YirTGXWuex9mxSyzXzZ45jCbP//CRM6eRKK4q9tll8L+QJTrrfT3RmxWSH4T/V6QQCp7OT8K38EAaN5P+NRQdJ9S/ZQnvG70mo3ZvPkgA3Itk45fuZNHMbO0GG2ctLNvYs0AJNjnC8g/DanoGEY45XxJH4kfb60uEvd72SA8FqHMRX/BK7mqvBByV6hd0EjsswG0jKU7Ygh8LySevTUjZT7Cj2hzb9mbzcYB7+gZ1Vao10CunWFjIWXulqyMHwYiRtqOStFxSnSH+yP0Xc6V3YDX4EteI=
  - secure: I44s3Nx+YaybkjGAFP2MaaJYL+Yv4ngCBYDyqzIFLdnGeuBlH2O4TlN1lJf9hWEVsUjAuftvzYWLuUdp5DGejXLB8wtKJ/3pn8eM+Fdj/lFCwn94/NJvov9rYMbPLdcPK94obI5dLSdjY3bmK+YN+O8cJlahwb/Ww6iIroT3fK4f2gP5Re87pSS2D6RIw5nzKFF0GJw1pOqAvk1CBCa9SDitMsKHSLBMmYzc+Pb83vcOzcbwBpF0RnK4OP1PDV6hgYv5jmZFR2JGxE7iHt+CDSFMSLsWHf9pRG5FROU6l11J/VF4ykOOtXxwrpEqGJqWdJmw49Jd+6sJfeymcnHnIxkdfiD2sdFvck2QlaG7oQy2e/0NiIgFLUSfNA5aVTrwwqMgzmTGTOBuPii4OIPMm7QVxllEh2++IPfWs8K6hV9ZqbIF0xXa9LeTsl+zxlUha1WiwdwukIc3A/V4l97T9eFHnMSz+0Ie4hCj1uEZu+zAdiVFGN0s9SCbkgnar2zw0rOFORI+q9LdDF1E0djuFBuH7sVAa7RIhsGQal+C98HUhdDYItqEYUlUUGXadQR9q6BHDqKUbWxr0DCC7+BEO2nw8zT2Tm7DGVuEve88pEt48KGAQTN4rzGvYPmkegm/Zzg1sos1cCHB5W+BORSLD2nWBetyh9fQ0u1N0fu+fto=
  - secure: EIY7auRtFmo1HH9vpa8gBMNC7nrcTSPGzGMVy1EW470z2xUhF0ABM7UzW13QrZ+OE81SQAwEv68JyMaNqQ76Xgm7lb6aUhpeIxq2II8RqzqU1rXElSjoROzSWyyFyL+MY2w84jG5VH/zdJCU768CHGcBeKjhiBq8/NEny/hAO02bjRoY6HmGogVOATPIRMrVdVez5IuFkU/vGfHQ9ntMWjrAj9DvoFwcJ2R3xKuCMaiUxv8VXThD5QbyyadZwwi1zdlP4wDjU9iwJUb0hyBHCByc1+2SZBuwwuZNhFFuUUcn28G/x7tOmoynt1I0PTq3F7jBFlrvFz+K1+uWGpdqysqPxn5e97tmR2n9kBxyjQYzmTIUuiAr3/fUuP0n2VdTug0+HbzyUO0LhwktAdjhHF9Cf58Po10JDk6hv72clYCvrp8sn2ZvisJ9L1Chote9xlIWTVaYMjYailji1ZOW+Fqsgk+1G+sNM0IiPNnoUrriJt/av6yn59o3AoS5uLZK3cEtor+eWxg3ALFHMlmm60Bnyniqp0qPIz44NM/1jKAGFwYqKzQv+zIxY0noc616YClh2OUjRzCUPgaHQJ0qTU5AtT6zf906VtApEm8BIbiYfG95AeKqFtux8jdajZflOiz6VTlccmgnNYDaKpEhEtQSlHurJev9BaJuw2wFrhM=
  - secure: Jf0g+OKHKXWY0fOiMsT54so59WD+RbBRxKwpzOvi6IA7YToC2g2L97GCrhls5isEwg1ROBhr9js6R7laSFxdTW0nq2OWJ5vYXx9z5lb3mnc2FLww5NlSQ6o5Djy0K8YLrsy3pG+p5HZmXFjDo9iLKXTL6nWk+u/vV2ep9ykIcspm9ZdwNS5Eu6xzFP5yTTCDjSmpQDHyergR//lOfTmKfKMbrtgYw2s9tm3O8B5dKTByYdfrQiGCkbqkf6jd3ncDGhCanei8stkz2crN6vyVOGQHHBELzZOEnBc3ZYA26LtT253eBYIO4hHLpkuZEhKR3Hw/YrxiXmhiSYvNUFk7GN7qyoiv3XxF5vfMpxNGvXZt0uku6uNb/ftmKzDMttKT0wCqr9MIRAK3bypLg4/GGbKuROMkMp4+LNmGakkJ5lwoggsOpyNwlpc1+u90iGH7XgJtlX9k3jqiGQQAahNaoPfMBUasmOU2fPLXd8Xi9mZFyMS+8BRVDlmjmys0ctPtb9EZtww8golOh82auV4wLcEr/z2ik1aiD2h0LTWeRZYgjXTe819emdfnnUxlzuve8C/smJRuX8HmvFqKHJ1pH6Ls38LwZDwJBGyCh79eLc0jB6j6BBev4VNDhA4oUiNXqClwzrFwG9/r3MUcoUheeHvrQxJ4NSNyiMa1WUp15tQ=
addons:
  sonarcloud:
    organization: cogpunk
    token:
      secure: s48t5kNEHmy3LUn7LEbR4/kYpwIondUrwa2diNS5yldZsn1GY/mQ7FlXABwij5BfJ4mq641LCRoCa/4wYvSUCDISNJKIapqXAjRqHxX6E9ZCi3JWVF28sesDlBJ55LNQUJGA0BBG0Xpi+jWLVAbuidt6PI5LrZfjye9dk+GWzp622tjCVGJ5hrcwi/DWswlSos09AvIMbRWvYjjVA+sBzGMhVJsudBlVAs0io/L1/vT541GnsPATaCab6Agu1u5rz7hqBdVoRFh+nWJr+Ac9IebsKxugQi3ggiYB802L6GDFs8oPEe5wAVV1p+9YxJRxHYt9E3guit7KH4JwAmSETNQYnREu2IBJ71na3ZrcPpYTUbhh+7uBJjK4nVidPhPthjs6/cibpmxzF4ZF9/g5iGN+Nfqw87cwp/mwdoiCQZRjHduxv4hQfSweWjb2HdRPvta4AreglYp0NVcZ/muTk6uOTUxxMBDzYpRr7jI5dlRsla26tQMKeCx97M8p0zGQZgYHaYycGeucPRKxrK+kIqYEM/i0Xx3OX/zvrdBaGoM7xbA2uwI0hQzl1GWn+8zMGyxNM9TlGB3eTtrClzDjXuTL2/kCRtOjUNi5uQgCa9kLiI+HIpqjjVT1RE/0I+ZNfMCnJUCgIrXbZLrdRdHBExg671vRTIZ3F/mDmgzy6j4=
install: skip
script: "./scripts/test"
before_deploy:
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
- gpg --fast-import --batch .travis/gpg.asc
deploy:
-
  provider: script
  script: "./scripts/deploy"
  skip_cleanup: true
  on:
    branch: main
-
  provider: script
  script: "./scripts/deploy"
  skip_cleanup: true
  on:
    tags: true
