#!/bin/bash

set -e

echo "Running custom test script on branch ${TRAVIS_BRANCH}"

if [ "${TRAVIS_BRANCH}" = "main" ]
then
	echo "Building, testing and pushing results to Sonar"
    mvn --settings "${TRAVIS_BUILD_DIR}/.travis/mvn-settings.xml" clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cogpunk_mathhammer -q -B
else
	echo "Building and testing"
    mvn clean install -q -B
fi
